### ISSUE TITLE
Hardware Errors Gridseed GC3355 - Voltage Modified

### ISSUE THREAD

**Issue by computeronix** [dmaxl/cgminer#34]
When using modified voltage Gridseed GC3355 massive hardware errors occur using frequency 1163 or lower.

If I switch back to cgminer 3.7.2 - dtbartle fork  https://github.com/dtbartle/cgminer-gc3355

Everything works fine.  Any ideas?  Any troublehsooting that can be done?  I like this new version because it is better updated and the API is more standardized

**Comment by computeronix** [comment]
I tried and received poor results

Out of 10 devices plugged in some would show 0 hash while others show 380

If o switch back to drbartle combiner 3.72 all 10 would be 480+

Next recommended mine?

Thank you again for the help

**Comment by dmaxl** [comment]
Can you post the configuration options you are passing to cgminer, in particular the gridseed-options? Also how has your unit been modded (i.e. which resistor on the voltage regulator has been replaced)? This fork supports a 'voltage' option for modded miners, but depending on how your unit has been modded will determine if that option needs to be set or not.

**Comment by computeronix** [comment]
The R52 resistor has been replaced with a 47 KOhm 0402 surface mount replacment. This increases
the voltage available to the mining chips, allowing them to run close to 1200 MHz(stock maxes out at
about 850 MHz), and increases the hashrate from the stock rate of 360 KH/s to over 480 KH/s


./cgminer --gridseed-options=baud=115200,freq=1163 --hotplug 30

Thanks for the updates,

Bill

Sent from my iPhone

On Mar 10, 2015, at 10:39 PM, dmaxl <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you post the configuration options you are passing to cgminer, in particular the gridseed-options? Also how has your unit been modded (i.e. which resistor on the voltage regulator has been replaced)? This fork supports a 'voltage' option for modded miners, but depending on how your unit has been modded will determine if that option needs to be set or not.

-

**Comment by dmaxl** [comment]
With that setup your command line looks fine. You can leave off the baud setting:

`cgminer --gridseed-options=freq=1163 --hotplug 30`

Does this still cause excessive hardware errors? In the cgminer UI does the displayed frequency match what you specified?
