### ISSUE TITLE
Gridseed Timeout

### ISSUE THREAD

**Issue by computeronix** [dmaxl/cgminer#36]
I know with cpuminer there is a command to issue a timeout for x amount of seconds after a device has stopped sharing for x amount of time.

Does cgminer have this option?  I did not see anything in the documentation but it is possible i skipped over it.

Thank you!

**Comment by dmaxl** [comment]
I think the closest option is `--scan-time <arg>`, which lets you set the maximum time (seconds) spent on a work unit before a new one is sent, but this is independent of when the last share was returned.

**Comment by computeronix** [comment]
Makes sense, if you were to set it any recommended settings?  900 seconds??

________________________________

**Comment by dmaxl** [comment]
The default should be fine in most cases, which is 60 seconds for SHA256
and 30 seconds for Scrypt. Perhaps on slower miners you could increase that
to give them more time to find a share before giving up. Keep in mind this
isn't the only factor cgminer uses to send new work, in particular it also
listens to the pool server either broadcasting a new block or asking for a
restart.
