### ISSUE TITLE
Gridseed Hash rate Spike

### ISSUE THREAD

**Issue by computeronix** [dmaxl/cgminer#37]
I have exactly the same devices plugged in (Gridseed Blade 40 chip)...however for some reason the hashrate on the last one sky rocketed...once I reboot it corrects itself.  Any ideas?

![screen shot 2015-03-30 at 9 08 57 am](https://cloud.githubusercontent.com/assets/11186939/6896754/9f6bf472-d6bc-11e4-9c9e-95cf863ada2a.png)

**Comment by computeronix** [comment]
Another spike on one of the workers

![screen shot 2015-03-31 at 11 37 38 am](https://cloud.githubusercontent.com/assets/11186939/6922613/641c0130-d79a-11e4-81a5-3997ed2d1bb5.png)

**Comment by dmaxl** [comment]
Apologies if this is too late, I seem to have missed the notification for this somehow.

I am guessing that the spikes are an artifact of how the driver calculates the hashrate. When work is sent and received the timestamps are compared and the rate calculated. This is sensitive to serial latency and thread locks of course. Occasionally this will cause a wild value to be reported for one work unit. After the miner successfully processes another share the hashrate should return to normal. The displayed hashrate has no affect on the miner regardless.

Is it happening frequently or excessively for you?

Also, not related to your question, it seems you are running with `--scan-serial` option on Linux. Did you try libusb and did it cause problems? Just curious as a point of feedback.
