### ISSUE TITLE
Gridseed : Strange Hashrate 

### ISSUE THREAD

**Issue by ltoinel** [dmaxl/cgminer#38]
Hi,

I started to mine Litecoin with cgminer-gc3355 and I discover this excellent up-to-date project ! 
I just compiled yesterday the sources and switched to this cgminer.

I have strange hashrate for my Gridseed :  261.58 KH/s with this version of cgminer vs 350KH/s for cgminer-gc3355

![hasrate](https://cloud.githubusercontent.com/assets/195268/7168879/f68426c4-e3c0-11e4-8032-4ee7128d0aa9.png)

I use the same starting options are the same : 
cgminer ./cgminer/cgminer --scrypt -o http://altmine.co:4444 --fix-protocol -u LYPPMSc1BN58keT649NUFg27tAsqAnssAEi -p password  --gridseed-options=baud=115200,freq=850,chips=5

I use a raspberry and the latest sources of the git.

Any idea ? 

Regards,

**Comment by dmaxl** [comment]
I just ran a small test here with one Gridseed 5 chip unit. Compiled latest master and ran with your options, CGminer reported 361.0 kh/s, however no work units in the short time I had it run.

261.58 KH/s is close to what you would get with the default clock frequency. On the CGminer screen can you confirm it displays "850 MHz" on the status line for your miner?
