### ISSUE TITLE
Zeus Detect: Test failed at /dev/ttyUSB0: got 00000000, should be 00038d26

### ISSUE THREAD

**Issue by RockyTV** [dmaxl/cgminer#40]
I've re-enabled my scrypt miner recently, and I get the following error when I run CGMiner:
`Zeus Detect: Test failed at /dev/ttyUSB0: got 00000000, should be 00038d26`

The miner is a Fury, and it was working before I changed the power supply because it stopped working.

This is my command-line command to start CGMiner:
`
/home/pi/cgminer-master/cgminer -o stratum+tcp://tcp://ca.simplemulti.com:3433 -u BTC_ADDRESS.worker -p x --scrypt --scan-serial zeus:auto --zeus-chips 6 --zeus-clock 358 --no-submit-stale --text-only --verbose 2>log-cgminer.txt
`

EDIT: using version 4.3.5.scrypt.2, on Raspbian.
Used --zeus-debug, and this is the [result](http://pastebin.com/raw.php?i=2165MqtY).

**Comment by dmaxl** [comment]
The debug output you linked doesn't include the test failed error, only shows it finding one miner. If you have a log including the error that would be helpful.

Also, I believe you have a typo in your command-line: repeated 'tcp://tcp://' for the pool address.

**Comment by RockyTV** [comment]
Alright. I've reinstalled my miner, and I'm still getting the same error.

Log: http://pastebin.com/raw.php?i=HdndF0vF

Command-line arguments: 
```
cgminer/cgminer --scrypt -o stratum+tcp://ca.simplemulti.com:3433 -u 1Q36xD4fouHKGUnxFKuUXAPWB1bugD2NmL.fury -p x --zeus-chips 6 --zeus-clock 358 --zeus-nocheck-golden --zeus-debug --scan-serial zeus:/dev/bus/usb/001/004 --no-submit-stale 2>cgminer.log
```

**Comment by RockyTV** [comment]
Somehow I managed to fix this issue.
